### ISSUE TITLE
Add project description

### ISSUE THREAD

**Issue by ep69** [NoName115/passwords_scripts#1]
Please add the project description as the first thing newcomer sees (what is it about, who is working on it, why we are doing it). Instructions for integration own pcl are great, but could be moved lower or just linked from the first page.

**Comment by NoName115** [comment]
What do you think about this:

Pcl-analyzer is a framework for testing and analysis various password checking libraries. This framework can load list of passwords, apply several transformations, check these passwords with implemented password checking libraries (CrackLib, PassWDQC, Zxcvbn, Pwscore, Passfault) and analyze their outputs.

The goal of this project is to quantify how well these password checking libraries are against passwords taken from real world data sets of leaked passwords.

This project was specified as RedHat Lab Project by Hubert Kario, the main coordinators of this project are Hubert Kario and Stanislav Židek. Author of code and implementation is Róbert Kolcún

??
